### ISSUE TITLE
Upcoming Packer v1.7.0 Release

### ISSUE THREAD

**Issue by nywilken** [huaweicloud/packer-builder-huaweicloud-ecs#27]
Hi! I'm a maintainer over at Packer and I wanted to reach out and let you know that we'll be releasing v1.7.0 tomorrow and it will include a backwards-breaking API change. This builder is already using the Packer Plugin SDK which means you should not be effected. But there is going to be a new version of the Packer Plugin SDK that I recommend you test against once released. 

That said, there's a little more legwork for you to do if you want your plugin to be compatible with the packer init feature we'll also be implementing in that release. We have an upgrade guide here: https://github.com/hashicorp/packer/blob/master/website/content/guides/1.7-plugin-upgrade.mdx

Let me know if you have any issues.

**Comment by AmisLee** [comment]
please hurry, huawei ecs plugin is not supporting packer >1.7.0

**Comment by AmisLee** [comment]
Error: Failed to initialize build "huaweicloud-ecs"
error initializing builder 'huaweicloud-ecs': The protocol of this plugin
(protocol version 4 and lower) was deprecated, please use a newer version of
this plugin.Or use an older version of Packer (pre 1.7) with this plugin.

**Comment by ShiChangkuo** [comment]
@AmisLee the new release [v0.3.0](https://github.com/huaweicloud/packer-builder-huaweicloud-ecs/releases/tag/v0.3.0) can support packer 1.7.0+, please try it.
