### ISSUE TITLE
Documentation mentions install from Releases, but there are no Releases in the repo

### ISSUE THREAD

**Issue by thiagoeh** [huaweicloud/packer-builder-huaweicloud-ecs#4]
The documentation mentions the installation using one release (instead of building the code by yourself), but there are no releases in the repository.

https://github.com/huaweicloud/packer-builder-huaweicloud-ecs/releases

**Comment by ShiChangkuo** [comment]
@thiagoeh Thanks for raising this, we have published two releases, please try them.
